### PR TITLE
Added option to specify build config

### PR DESCRIPTION
**Pull request by trojanc**
This pull request allows the user to specify build config for cordova.
This should take care of many of the other tickets requesting a way to specify build parameters for ios and other platforms

### CODE REVIEW

**Comment by trojanc** [comment]
This isn't tested thoroughly at all! I think it's only going to work for newer cordova versions that support using the `build.json`. I thought of adding it to each platform's plugin, and then though of just adding the config with the create plugin, since the config can be shared by any platform.

Right now it merges the `build.config` file if it exists, or creates a new one if it doesn't.
If the `buildConfig` option is not specified, this addition will not do anything and should still behave as it used to.

**Comment by SamVerschueren** [comment]
Hi @trojanc! Thanks for you PR! Sorry that it took so long, kinda lost this one out of sight. Could you point me to the docs of this feature? I've never used it to be honest.

**Comment by trojanc** [comment]
Hi, the options for build.json is at each platforms documentation
https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#using-buildjson
https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#using-buildjson
https://cordova.apache.org/docs/en/latest/guide/platforms/win8/index.html#signing-an-app

**Comment by thejamespower** [comment]
When can we expect this to be supported? Is there another way to get iOS Code Signing to work with this plugin?

**Pull request closed without merging**
